import { Address } from "viem";

export interface PrimaryNameProps {
    /**
     * Registered name:
     * e.g legend.root
     */
    name?: string;

    /**
     * domainId = namehash(`${ownerId.slice(2)}.addr.reverse`)
     */
    domainId?: string;
    resolverAddress?: Address;

    /**
     * The data generated by the encodeFunctionData
     */
    addressRecord?: Address;
}
