query NamesByAddress(
  $expiryDate_gte: BigInt = "0"
  $expiryDate_lt: BigInt = "0"
  $first: Int = 1000
  $skip: Int = 0
  $name: String = ""
  $id: ID = ""
  $orderDirection: OrderDirection = desc
  $orderBy: Domain_orderBy = registration__registrationDate
  $ensName: String = ""
  $sortByLength: Boolean = false
) {
  domains(
    where: {
      wrappedOwner_: { id: $id }
      name_contains: $name
      expiryDate_gte: $expiryDate_gte
      expiryDate_lt: $expiryDate_lt
    }
    first: $first
    skip: $skip
    orderBy: $orderBy
    orderDirection: $orderDirection
  ) {
    id
    labelName
    labelhash
    name
    isMigrated
    parent {
      name
    }
    createdAt
    resolvedAddress {
      id
    }
    owner {
      id
    }
    registrant {
      id
    }
    wrappedOwner {
      id
    }
    registration {
      cost
      registrationDate
      expiryDate
    }
    wrappedDomain {
      expiryDate
      fuses
    }
    resolver {
      texts
      coinTypes
    }
  }
}

query TotalDomains(
  $first: Int = 1000
  $skip: Int = 0
  $id: ID = ""
  $name: String = ""
  $expiryDate_gt: BigInt = "0"
) {
  domains(
    first: $first
    skip: $skip
    where: {
      wrappedOwner_: { id: $id }
      name_contains: $name
      expiryDate_gt: $expiryDate_gt
    }
  ) {
    name
    wrappedOwner {
      id
    }
  }
}
